### PR TITLE
B-515: fix ignored vlan_id

### LINKED ISSUE #515: vlan_id is ignored with opennebula_virtual_network and ovswitch
### Description

When I set `vlan_id`, it is ignored. Terraform acts as everything is well, but there is no VLAN set in OpenNebula.

There is nothing relevant in oned log. I'm using CE version, same problem on 6.4 and 6.6 (I upgraded to 6.6. when it didn't work).

It was working on some of previous versions, but unfortunately I'm not sure which was it. I didn't need it in couple months and memory is fuzzy.

### Terraform and Provider version

```
❯ terraform -v
Terraform v1.6.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/dns v3.4.0
+ provider registry.terraform.io/nbering/ansible v1.0.4
+ provider registry.terraform.io/opennebula/opennebula v1.3.1
```

### Affected resources and data sources

-  opennebula_virtual_network

### Terraform configuration

```HCL
terraform {
  required_version = "1.6.6"
  required_providers {
    opennebula = {
      source  = "opennebula/opennebula",
      version = "1.3.1"
    }
  }
}

variable "one_endpoint" {}
variable "one_username" {}
variable "one_password" {}
variable "one_flow_endpoint" {}

provider "opennebula" {
  endpoint      = var.one_endpoint
  flow_endpoint = var.one_flow_endpoint
  username      = var.one_username
  password      = var.one_password
}

resource "opennebula_virtual_network" "reproduce" {
  name        = "reproduce-public"
  permissions = "660"
  group       = "oneadmin"
  type        = "ovswitch"
  bridge      = "ovs-pub"
  vlan_id     = 1458

  dns     = "10.128.2.1"
  gateway = "10.128.2.1"

  cluster_ids = [0]
}
```

### Expected behavior

VLAN should be set in OpenNebula as instructed in configuration.

### Actual behavior

VLAN is empty.

### Steps to Reproduce

1. create `main.tf` witch content fo terraform configuration (setup your variables ofc)
2. terraform init
3. terraform apply
4. check created network in opennebula

Here is output of `terraform apply`:

```
❯ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # opennebula_virtual_network.reproduce will be created
  + resource "opennebula_virtual_network" "reproduce" {
      + automatic_vlan_id = (known after apply)
      + bridge            = "ovs-pub"
      + cluster_ids       = [
          + 0,
        ]
      + default_tags      = (known after apply)
      + dns               = "10.128.2.1"
      + gateway           = "10.128.2.1"
      + gid               = (known after apply)
      + gname             = (known after apply)
      + group             = "oneadmin"
      + guest_mtu         = 1500
      + id                = (known after apply)
      + mtu               = 1500
      + name              = "reproduce-public"
      + permissions       = "660"
      + physical_device   = (known after apply)
      + reservation_ar_id = -1
      + reservation_vnet  = -1
      + security_groups   = (known after apply)
      + tags_all          = (known after apply)
      + type              = "ovswitch"
      + uid               = (known after apply)
      + uname             = (known after apply)
      + vlan_id           = "1458"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

opennebula_virtual_network.reproduce: Creating...
opennebula_virtual_network.reproduce: Creation complete after 5s [id=77]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

and here is network in ONE:

```
❯ onevnet show reproduce-public
VIRTUAL NETWORK 77 INFORMATION
ID                       : 77
NAME                     : reproduce-public
USER                     : oneadmin
GROUP                    : oneadmin
LOCK                     : None
CLUSTERS                 : 0
BRIDGE                   : ovs-pub
STATE                    : READY
VN_MAD                   : ovswitch
AUTOMATIC VLAN ID        : NO
AUTOMATIC OUTER VLAN ID  : NO
USED LEASES              : 0

PERMISSIONS
OWNER                    : um-
GROUP                    : um-
OTHER                    : ---

VIRTUAL NETWORK TEMPLATE
BRIDGE="ovs-pub"
BRIDGE_TYPE="openvswitch"
DNS="10.128.2.1"
GATEWAY="10.128.2.1"
GUEST_MTU="1500"
MTU="1500"
OUTER_VLAN_ID=""
PHYDEV=""
SECURITY_GROUPS="0"
VLAN_ID=""
VN_MAD="ovswitch"

ADDRESS RANGE POOL

LEASES
AR  OWNER        MAC    IP PORT_FORWARD   IP6

VIRTUAL ROUTERS

VIRTUAL MACHINES
UPDATED                  :
OUTDATED                 :
ERROR                    :
```

### Debug output

https://gist.github.com/kepi/c8d8a8af6fe09cb05ec5bf9cafe01e0a

### Panic output

_No response_

### Important factoids

I'm using `oneadmin` account for network definition, so ACL shouldn't be issue. 

### References

_No response_

### PR DESCRIPTION
**Pull request by treywelsh**
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

Allow to optionally set a `vlan_id` value for ovswitch
Related older PR #407  

### References

Close #515

### New or Affected Resource(s)

- opennebula_virtual_network

### Checklist

- [ ] I have created an issue and I have mentioned it in `References`
- [ ] My code follows the style guidelines of this project (use `go fmt`)
- [ ] My changes generate no new warnings or errors
- [ ] I have updated the unit tests and they pass succesfuly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation (if needed)
- [ ] I have updated the changelog file

### CODE REVIEW

**Comment by treywelsh** [comment]
coucou

**Review by frousselet — APPROVED** [review]

File: opennebula/resource_opennebula_virtual_network.go [hunk 1]
```diff
@@ -802,15 +802,19 @@ func generateVn(d *schema.ResourceData) (string, error) {
...
-		} else if vlanid, ok := d.GetOk("vlan_id"); ok {
-			tpl.Add(vnk.VlanID, vlanid.(string))
-		} else {
-			return "", fmt.Errorf("You must specify a 'vlan_id' or set the flag 'automatic_vlan_id'")
-		}
+	vlanSet := false
+	if d.Get("automatic_vlan_id").(bool) {
+		tpl.Add("AUTOMATIC_VLAN_ID", "YES")
+		vlanSet = true
+	} else if vlanid, ok := d.GetOk("vlan_id"); ok {
```
Comment (dgarcia18) [inline opennebula/resource_opennebula_virtual_network.go:809]: According to OpenNebula docs on ovswitch vnets, automatic_vlan_id should be ignored in case vlan_id is defined (https://docs.opennebula.io/6.10/open_cluster_deployment/networking_setup/openvswitch.html#defining-open-vswitch-network). Meaning that, if both params are defined, vlan_id should have priority => vlan_id should be checked first

**Comment by aleixrm** [comment]
hey @treywelsh I've added @dgarcia18 's suggestion and some tests in this PR: https://github.com/OpenNebula/terraform-provider-opennebula/pull/581

Feel free to take a look and merge it to this branch, I think that with those changes this PR could be merged 👍🏼 Thanks!

File: opennebula/resource_opennebula_virtual_network.go (hunk 1 above)
Comment (aleixrm) [reply opennebula/resource_opennebula_virtual_network.go:809]: hey @dgarcia18 good catch! In any case, setting both attributes will raise a conflict error in the provider, but I've corrected it just in case and added a test for checking this case 👍🏼 
```
"automatic_vlan_id": conflicts with vlan_id
 Error: Conflicting configuration arguments
```
