### PR TITLE
F #239: Add default value for volatile_format

### LINKED ISSUE #239: [resource][VM] Error when updating a volatile disk
Acceptance tests are failing wit the error below, because no default value is defined for `volatile_format` attribute:

```
=== RUN   TestAccVirtualMachineDiskUpdate
    testing.go:654: Step 1 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: opennebula_virtual_machine.test
          ...
          disk.0.target:          "vda" => "vda"
          disk.0.volatile_format: "raw" => ""
          disk.0.volatile_type:   "swap" => "swap"
          ...
        
        STATE:
        
        opennebula_image.image1:
          ...
        opennebula_image.image2:
          ...
        opennebula_virtual_machine.test:
          ...
          disk.0.target = vda
          disk.0.volatile_format = raw
          disk.0.volatile_type = swap
          ...
--- FAIL: TestAccVirtualMachineDiskUpdate (63.85s)
```

I think the problem is in the `volatile_format` definition, as no default value is set but the validate function will fail if the value is not include in `validtypes`, hence it will fails when the value is empty:

```
"volatile_format": {
	Type:        schema.TypeString,
	Optional:    true,
	Description: "Format of the volatile disk: raw or qcow2.",
	ValidateFunc: func(v interface{}, k string) (ws []string, errors []error) {
		validtypes := []string{"raw", "qcow2"}
		value := v.(string)

		if inArray(value, validtypes) < 0 {
			errors = append(errors, fmt.Errorf("Format %q must be one of: %s", k, strings.Join(validtypes, ",")))
		}

		return
	},
},
```

### PR DESCRIPTION
**Pull request by christian7007**

### CODE REVIEW

File: opennebula/shared_schemas.go [hunk 1]
```diff
@@ -106,6 +106,7 @@ func diskFields(customFields ...map[string]*schema.Schema) map[string]*schema.Sc
 		"volatile_format": {
 			Type:        schema.TypeString,
 			Optional:    true,
+			Default:     "raw",
```
Comment (jaypif) [inline opennebula/shared_schemas.go:109]: Can you please update the description to precise the default value ? thank you

Comment (christian7007) [reply opennebula/shared_schemas.go:109]: Sorry I missed that one. Updated.

**Review by treywelsh — APPROVED** [review]

**Comment by peterloeffler** [comment]
For me it looks like setting this default breaks any usage of disks other than using `volatile_format`. It cannot be used together with image_id. Or am I getting somthing wrong here?
https://github.com/OpenNebula/terraform-provider-opennebula/pull/242#issuecomment-1104067835
