### PR TITLE
F-228: add `opennebula_group_admins` resource

### LINKED ISSUE #228: Creating user as group admin for created group - chicken/egg problem?
Hi,

I'm not sure if I'm missing something obvious, but I want to create new user and group in OpenNebula. And set that new user as admin for created group.

From documentation, only possibility seems to be something like this: 

```hcl
resource "opennebula_group" "group" {
  name                  = "example"
  admins               = [opennebula_user.user.id]
  template              = <<EOT
SUNSTONE = [
  DEFAULT_VIEW = "cloud",
  GROUP_ADMIN_DEFAULT_VIEW = "groupadmin",
  GROUP_ADMIN_VIEWS = "cloud,groupadmin",
  VIEWS = "cloud"
]
EOT
  delete_on_destruction = true
}

resource "opennebula_user" "user" {
  name          = "example"
  password      = random_password.password.result
  auth_driver   = "core"
  primary_group = opennebula_group.group.id
}

```

But problem is, that:

1. I can't create user with primary group which doesn't exist.
2. And I can't create group with admin which doesn't exist... 
 
I tried to work around this with `data` instead of `resource`. And I also tried adding *ACL* instead of setting user as primary, but that doesn't work at least for *Sunstone*.

I suppose one possibility at the moment might be using different group as primary and use obsolete `users` in `opennebula_group`. But as this is obsoleted, this wont be working in future. I would also like to have user only in single (primary) group.

From quick glance, it would be best to add something like `group_admin_for` array in `opennebula_user`.

Edit: using 0.4.1 provider

### PR DESCRIPTION
**Pull request by treywelsh**
This PR adds the new resource `opennebula_group_admins`

### CODE REVIEW

File: opennebula/resource_opennebula_group.go [hunk 1]
```diff
@@ -185,7 +186,18 @@ func resourceOpennebulaGroupRead(d *schema.ResourceData, meta interface{}) error
 		}
 	}
 
-	err = d.Set("admins", group.Admins.ID)
+	// Read only configured admins in current resource to avoid conflict
+	// with opennebule_admins
+	configuredAdmins := schema.NewSet(schema.HashInt, d.Get("admins").([]interface{}))
+	var appliedAdmins []interface{}
+	for _, id := range group.Admins.ID {
```
Comment (frousselet) [inline opennebula/resource_opennebula_group.go]: User might use Terraform `lifecycle`/`ignore_changes` [meta-argument](https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes) to prevent resource attribute overlapping.

In this case:

```hcl
resource "opennebula_group" "my_group" {
  # ...

  lifecycle = {
    ignore_changes = [
      admins
    ]
  }
}
```

**Comment by treywelsh** [comment]
documentation and CHANGELOG updated

**Review by frousselet — APPROVED** [review]
LGTM

**Comment by treywelsh** [comment]
tiny acceptance test added, CI for 5.12 ONE release pass
