### PR TITLE
B #537: Make Virtual Router's instances re-contextable.

### LINKED ISSUE #537: Impossible to update context of Virtual Router instances
### Description

After Virtual Router's instance(s) are created, any attempt of CONTEXT vector update causes panic.

```
panic: interface conversion: interface {} is nil, not []interface {}
```

This is particularly annoying because you can deploy fully working VR, but you can't reconfigure it, at the same time VR supports many features that can be dynamically enabled/disabled and reconfigured.

### Terraform and Provider version

```
Terraform v1.7.5
on linux_amd64
+ provider registry.terraform.io/opennebula/opennebula v1.4.0
```

### Affected resources and data sources

`opennebula_virtual_router_instance`

### Terraform configuration

```HCL
resource "opennebula_virtual_router_instance" "test" {
  name = "test"
  context = {
    ONEAPP_VNF_DNS_ENABLED = "NO"
  }
  virtual_router_id = opennebula_virtual_router.test.id
}
```

### Expected behavior

When I change `ONEAPP_VNF_DNS_ENABLED` from "NO" to "YES" and run `terraform apply` I want the VM re-contexted + no errors.

### Actual behavior

```
panic: interface conversion: interface {} is nil, not []interface {}
```

### Steps to Reproduce

1. Define the usual `opennebula_virtual_router`, `opennebula_virtual_router_instance_template`, and `opennebula_virtual_router_instance`, then apply.
2. Change any context variable of the `opennebula_virtual_router_instance`, then apply.

### Debug output

_No response_

### Panic output

_No response_

### Important factoids

The `resourceOpennebulaVirtualMachineRead` method seems to be throwing errors.

### References

_No response_

### PR DESCRIPTION
**Pull request by sk4zuzu**
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

This is a fix that enables Virtual Router instances to be updated/re-contexted.

### References

#537 

### New or Affected Resource(s)

- opennebula_virtual_router_instance

### Checklist

- [x] I have created an issue and I have mentioned it in `References`
- [x] My code follows the style guidelines of this project (use `go fmt`)
- [x] My changes generate no new warnings or errors
- [x] I have updated the unit tests and they pass succesfuly
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the documentation (if needed)
- [x] I have updated the changelog file

### CODE REVIEW

File: opennebula/resource_opennebula_virtual_machine.go [hunk 1]
```diff
@@ -605,22 +605,25 @@ func resourceOpennebulaVirtualMachineRead(ctx context.Context, d *schema.Resourc
...
-		if _, ok := d.GetOk("template_nic"); !ok {
-			d.Set("template_nic", []interface{}{})
-		}
-		if _, ok := d.GetOk("template_tags"); !ok {
-			d.Set("template_tags", map[string]interface{}{})
-		}
-		if _, ok := d.GetOk("template_section_names"); !ok {
-			d.Set("template_section_names", map[string]interface{}{})
+		// NOTE: The template_* attributes are not defined for Virtual Router instances (VMs).
+		if _, ok := d.GetOk("template_id"); ok {
```
Comment (treywelsh) [inline opennebula/resource_opennebula_virtual_machine.go:609]: why adding this check ?
It's possible to inherit disks and tags from virtual router instance template, right ?
However, maybe that `template_nic` code is not relevant here.

The schema description (`template_nic` etc.) is added via this func: https://github.com/OpenNebula/terraform-provider-opennebula/blob/master/opennebula/resource_opennebula_virtual_router_instance.go#L41

**Review by treywelsh — COMMENTED** [review]
I may not know OpenNebula as well as you so feel free to correct me if I'm missing something in my comment

File: opennebula/resource_opennebula_virtual_machine.go (hunk 1 above)
Comment (sk4zuzu) [reply opennebula/resource_opennebula_virtual_machine.go:609]: I'm not completely sure if this implementation is correct either, hence the review :smiling_face_with_tear:. But, if you look at the `opennebula_virtual_router_instance` resource, there is no `template_id` argument :thinking:. At the same time VR instances are processed with code reused from handling VMs (that have optional `template_id`  argument), so the `d.Set("template_id", templateID)`  basically causes panic in this specific case context is updated. Perhaps I should rephrase the comment as I confused attributes with arguments. :thinking:

Comment (sk4zuzu) [reply opennebula/resource_opennebula_virtual_machine.go:609]: Looking again at provider documentaion I think you're right about other template_* args, so I will re-evaluate, but the `template_id` one is for sure causing problems.

Comment (sk4zuzu) [reply opennebula/resource_opennebula_virtual_machine.go:609]: @treywelsh Hi, I've been MIA sorry. So indeed attributes defined here https://github.com/OpenNebula/terraform-provider-opennebula/blob/master/opennebula/shared_schemas.go#L20 can be kept and they don't cause panics, `template_id` and `template_nic` on the other hand do. :face_holding_back_tears:

**Review by treywelsh — APPROVED** [review]
