### PR TITLE
B-205: fix vm user_template management

### LINKED ISSUE #205: [resource][vm] attributes update errors
The problem is present in the 0.3.0 and still here in 0.4.0 releases.

To reproduce, create the VM applying this with the 0.4.0 release of the provider:
```
resource "opennebula_virtual_machine" "test" {
  name        = "test-virtual_machine"
  group       = "oneadmin"
  permissions = "642"
  memory      = 128
  cpu         = 1

  sched_requirements = "CLUSTER_ID!=\"123\""
  description = "this is a test"
  tags = {
    test   = "1"
    customer = "test"
  }

  timeout = 5
}
```
Then modify a value from the `tags` section and apply again:
```
│ Error: OpenNebula error [INTERNAL]: [one.vm.update] Cannot update template. Parse error: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 942879269, columns 124:135
```
It's due to the fact that the provider send the `sched_requirement` element with the value `"CLUSTER_ID!="123""`.
Double quotes are not escaped anymore.

The provider manage internally a VM attribute section named `USER_TEMPLATE` and during the process the escapment is interpreted.
It may disappear during the XML processing in Goca (API mapping of ONE in Golang). I need to investigate on this part.

Anyway I'll first propose a fix in the provider that escape the values retrieved from cloud side.

### PR DESCRIPTION
**Pull request by treywelsh**
This PR fix several problems in refactoring the whole `USER_TEMPLATE` part management.

It uses the replacement behavior of the `one.vm.update` XML-RPC method and update the `USER_TEMPLATE` content read from ONE.
Among others it:
- re-escape double quotes
- fix some careless mistake, like using the `TEMPLATE` section instead of the `USER_TEMPLATE`
- add acceptance tests steps

This PR should allow to add new tags, update them, and remove them from the `USER_TEMPLATE`

### CODE REVIEW

**Comment by treywelsh** [comment]
The acceptance test doesn't reproduce the problem I tried to fix in this PR for now

File: opennebula/resource_opennebula_virtual_machine.go [hunk 1]
```diff
@@ -1006,83 +1005,88 @@ func resourceOpennebulaVirtualMachineUpdate(d *schema.ResourceData, meta interfa
...
-			return err
-		}
-	}
-
-	if d.HasChange("tags") {
-		tagsInterface := d.Get("tags").(map[string]interface{})
-		for k, v := range tagsInterface {
-			vmInfos.UserTemplate.Del(strings.ToUpper(k))
-			vmInfos.UserTemplate.AddPair(strings.ToUpper(k), v.(string))
+		// deleted tags
```
Comment (jaypif) [inline opennebula/resource_opennebula_virtual_machine.go]: delete

**Review by jaypif — APPROVED** [review]

**Review by jaypif — APPROVED** [review]

**Review by jaypif — APPROVED** [review]
