### PR TITLE
enhance template schema

### LINKED ISSUE #23: Templates always update even without changes.
I'm using the template resource and have found it impossible to get the resource to pass through a `terraform apply` without updating.

I've updated to the latest changes in master, and at first I experienced whitespace issues which were giving false positives. After fixing those, the diff shows no actual differences in the template but still requires an update.

I even used a template data source and passed in the very same template but it still updates each time.

Looking at the code, it's clear that there it is just a simple string comparison, so it is no real suprise it doesn't work reliably. 

I noticed there was talk in another issue of creating a schema for the template which would help, but if passing a string in as a template is to be retained, there should be a way of normalising the template to avoid whitespace differences affecting the comparison.

#15

### PR DESCRIPTION
**Pull request by treywelsh**
Enhance template schema and share common parts with VM entity

Solve issue #15
And fix #23

### CODE REVIEW

File: opennebula/resource_opennebula_template.go [hunk 1]
```diff
@@ -34,8 +34,24 @@ func resourceOpennebulaTemplate() *schema.Resource {
...
+			},
+			"cpu":      cpuSchema(),
+			"vcpu":     vcpuSchema(),
+			"memory":   memorySchema(),
+			"context":  contextSchema(),
+			"disk":     diskSchema(),
+			"graphics": graphicsSchema(),
+			"nic":      nicSchema(),
+			"os":       osSchema(),
+			"pairs": {
```
Comment (jaypif) [inline opennebula/resource_opennebula_template.go]: this is very close to tags (#22 ). Can you rename this as "tags" instead of pairs ?

File: opennebula/resource_opennebula_template.go [hunk 2]
```diff
@@ -34,8 +34,24 @@ func resourceOpennebulaTemplate() *schema.Resource {
...
+				Deprecated:  "use other schema sections instead.",
+			},
+			"cpu":      cpuSchema(),
+			"vcpu":     vcpuSchema(),
+			"memory":   memorySchema(),
+			"context":  contextSchema(),
+			"disk":     diskSchema(),
+			"graphics": graphicsSchema(),
+			"nic":      nicSchema(),
+			"os":       osSchema(),
```
Comment (jaypif) [inline opennebula/resource_opennebula_template.go:49]: can you add:
- "hypervisors" (simple string with a validate functions) to support "KVM, vCenter or LXD"
- "SCHED_REQUIREMENTS" (as a string)
- "User inputs" section (this is to manage if cpu, vcpu or memory values are fixed or not)
- "description": to have a description part
- "vmgroup": like it is the case for VM

File: opennebula/resource_opennebula_template_test.go [hunk 3]
```diff
@@ -25,6 +25,7 @@ func TestAccTemplate(t *testing.T) {
 					resource.TestCheckResourceAttr("opennebula_template.template", "name", "terra-tpl"),
 					resource.TestCheckResourceAttr("opennebula_template.template", "permissions", "660"),
 					resource.TestCheckResourceAttr("opennebula_template.template", "group", "oneadmin"),
+					resource.TestCheckResourceAttr("opennebula_template.template", "cpu", "0.5"),
```
Comment (jaypif) [inline opennebula/resource_opennebula_template_test.go:27]: you should add a test function for any possible parameter (context, os, graphics, ...)

File: opennebula/shared_schemas.go [hunk 4]
```diff
@@ -0,0 +1,444 @@
...
+	os := d.Get("os").(*schema.Set).List()
+	//vmos := make([]vmOs, len(os))
+	for i := 0; i < len(os); i++ {
+		osconfig := os[i].(map[string]interface{})
+		tpl.AddOS(vmk.Arch, osconfig["arch"].(string))
+		tpl.AddOS(vmk.Boot, osconfig["boot"].(string))
+	}
+
+	//Generate VM Group definition
+	vmgroup := d.Get("vmgroup").(*schema.Set).List()
```
Comment (jaypif) [inline opennebula/shared_schemas.go]: not define in schema. I think this is the reason why CI is not passing

**Review by jaypif — CHANGES_REQUESTED** [review]
Very grat work!
However some minor changes should be done:
- can you rebase to add vmgroup ?
- Can you also update template with new parameters (specific to templates) ?

Thanks

File: opennebula/resource_opennebula_template.go (hunk 2 above)
Comment (treywelsh) [reply opennebula/resource_opennebula_template.go:49]: Just to be sure that I don't make any mistake, all of these attributes should be shared between VM and Template schemas ?

For user input, it should be a TypeMap (we can fill USER_INPUT with custom values), as for Tags schemas. Right ?

Thank you :)

Comment (jaypif) [reply opennebula/resource_opennebula_template.go:49]: yes

File: opennebula/resource_opennebula_template_test.go (hunk 3 above)
Comment (treywelsh) [reply opennebula/resource_opennebula_template_test.go:27]: I still need to add some tests, but anyway, for dynamic parts as context or user_inputs it may require a bit more of work are they can take custom values

File: opennebula/shared_schemas.go [hunk 5]
```diff
@@ -0,0 +1,579 @@
...
+		Description: "Context variables",
+	}
+}
+
+func graphicsSchema() *schema.Schema {
+	return &schema.Schema{
+		Type:        schema.TypeList,
+		Optional:    true,
+		Computed:    true,
+		MinItems:    0,
```
Comment (jaypif) [inline opennebula/shared_schemas.go]: useless because it is Optional ;)

File: opennebula/shared_schemas.go [hunk 6]
```diff
@@ -0,0 +1,579 @@
...
+	}
+}
+
+func vmGroupSchema() *schema.Schema {
+	return &schema.Schema{
+		Type:        schema.TypeList,
+		Optional:    true,
+		Computed:    true,
+		ForceNew:    true,
+		MinItems:    0,
```
Comment (jaypif) [inline opennebula/shared_schemas.go]: useless because it is Optional ;)

File: opennebula/shared_schemas.go [hunk 7]
```diff
@@ -0,0 +1,579 @@
...
+	}
+
+	descr, ok := d.GetOk("description")
+	if ok {
+		tpl.Add(vmk.Description, descr.(string))
+	}
+
+	hyp, ok := d.GetOk("hypervisor")
+	if ok {
+		tpl.AddPair("HYPERVISOR", hyp.(string))
```
Comment (jaypif) [inline opennebula/shared_schemas.go]: maybe force "ToLower" here as OpenNebula values are in lower case

**Comment by treywelsh** [comment]
Ok, since last review I made a mistake in my last push, sorry for the mess.

In this last revision of my PR I added this new behavior:
When there is some existing disks and NICs in the template being instantiaed (identified by template_id), I add them to the new template to not loose them.
All new disk and nics will be appended after.

This way of merging the data from an template with data from the tf file (previously implemented for Context part to solve issue #10 )  is a custom behavior that we add to the terraform plugin.

For all other vectors than disk, nic, and context, as they have a small number of attributes (graphics, os ...), old values are overwritten.

To understand why we need to do this, take a look at the default behavior of the OpenNebula method that we use to instantiate an existing template, documented here:
https://docs.opennebula.org/5.10/integration/system_interfaces/api.html#one-template-instantiate

**Review by jaypif — CHANGES_REQUESTED** [review]
doc update is missing.
you change template and VM resource parameter. Your PR must have a commit with doc update.


Thanks

File: website/docs/r/template.html.markdown [hunk 8]
```diff
@@ -16,15 +16,67 @@ a new template will be created. When destroyed, that template will be removed.
 ## Example Usage
 
 ```hcl
-data "template_file" "templatetpl" {
-  template = "${file("template-tpl.txt")}"
+data "template_file" "cloudinit" {
```
Comment (jaypif) [inline website/docs/r/template.html.markdown]: to be removed

File: website/docs/r/template.html.markdown [hunk 9]
```diff
@@ -16,15 +16,67 @@ a new template will be created. When destroyed, that template will be removed.
...
+
+  user_inputs {
+    TITLE="M|text|some text",
+  }
+
+  context {
+    TITLE="$TITLE",
+    NETWORK = "YES"
+    HOSTNAME = "$NAME"
+    USER_DATA = "${data.template_file.cloudinit.rendered}"
```
Comment (jaypif) [inline website/docs/r/template.html.markdown]: to be removed or replaced by a correct variable

File: website/docs/r/template.html.markdown [hunk 10]
```diff
@@ -33,7 +85,7 @@ with template file `template-tpl.txt`:
 CPU = 1
```
Comment (jaypif) [inline website/docs/r/template.html.markdown]: remove this txt file as it was only needed by the deprecated parameter

File: website/docs/r/template.html.markdown [hunk 11]
```diff
@@ -53,6 +105,16 @@ The following arguments are supported:
 * `template` - (Required) Text describing the OpenNebula template object, in Opennebula's XML string format.
```
Comment (jaypif) [inline website/docs/r/template.html.markdown]: now it is deprecated and optional.

File: website/docs/r/virtual_machine.html.markdown [hunk 12]
```diff
@@ -144,6 +161,26 @@ The following attribute are exported:
 * `state` - State of the virtual machine.
 * `lcmstate` - LCM State of the virtual machine.
 
+## Instantiate from a template
```
Comment (jaypif) [inline website/docs/r/virtual_machine.html.markdown:144]: This is quite confusing for this first version.

If the user instantiate a `template_id` here is the behavior:
* for all parameters excepted `context`: parameters present in VM overrides parameters defined in template
* for context: it merges them

Thanks

**Review by jaypif — CHANGES_REQUESTED** [review]

**Comment by jaypif** [comment]
all goo thanks!

**Review by jaypif — APPROVED** [review]
