### PR TITLE
B-203: vnet: check empty ar

### LINKED ISSUE #203: [resource][datasource][virtual network] no ar field cause crash
When no AR are defined for the virtual network resource, or if we use a datasource (which has no `ar` field) the provider crash at read step.
Acceptance test should be updated to cover this case

Introduced by #141

### PR DESCRIPTION
**Pull request by treywelsh**
Test AR attribute for nil

Close #203

### CODE REVIEW

File: opennebula/resource_opennebula_virtual_network.go [hunk 1]
```diff
@@ -788,7 +788,11 @@ func resourceOpennebulaVirtualNetworkRead(d *schema.ResourceData, meta interface
 func flattenVnetARs(d *schema.ResourceData, vn *vn.VirtualNetwork) error {
 
 	ARSet := make([]map[string]interface{}, 0, len(vn.ARs))
-	ARConfigs := d.Get("ar").(*schema.Set).List()
+	ARIf := d.Get("ar")
```
Comment (jaypif) [inline opennebula/resource_opennebula_virtual_network.go]: why not performing this check before calling the function ?

**Review by jaypif — CHANGES_REQUESTED** [review]

**Review by jaypif — APPROVED** [review]
