### PR TITLE
B-149: VDC: fix flattening and tests

### LINKED ISSUE #149: [Virtual Data Center] error in logs
```
2021/08/27 21:34:00 [ERROR] setting state: Invalid address to set: []string{"zones", "0", "HostIDs"}
```

### PR DESCRIPTION
**Pull request by treywelsh**

### CODE REVIEW

File: opennebula/resource_opennebula_virtual_data_center_test.go [hunk 1]
```diff
@@ -105,14 +114,34 @@ func testAccCheckVirtualDataCenterZones(zoneidx int, expected vdcZone) resource.
...
+					if k == "id" {
+						if zone[k].(int) != expected[k].(int) {
+							return fmt.Errorf("VDC (%s) Zones are not the expected ones, got %+v instead of %+v", rs.Primary.ID, zone, expected)
+						}
+						continue
+					}
+					// compare slice of IDs
+					ids := zone[k].([]int)
+					if len(ids) != len(expected[k].([]int)) {
+						return fmt.Errorf("VDC (%s) Zones are not the expected ones, got %+v instead of %+v", rs.Primary.ID, zone, expected)
```
Comment (jaypif) [inline opennebula/resource_opennebula_virtual_data_center_test.go]: maybe change the error message to have something more understandable.

File: opennebula/resource_opennebula_virtual_data_center_test.go [hunk 2]
```diff
@@ -105,14 +114,34 @@ func testAccCheckVirtualDataCenterZones(zoneidx int, expected vdcZone) resource.
...
+					}
+					expectedIDs := expected[k].([]int)
+					for i := range ids {
+						if ids[i] != expectedIDs[i] {
+							return fmt.Errorf("VDC (%s) Zones are not the expected ones, got %+v instead of %+v", rs.Primary.ID, zone, expected)
```
Comment (jaypif) [inline opennebula/resource_opennebula_virtual_data_center_test.go]: same here

**Review by jaypif — APPROVED** [review]
