### PR TITLE
B #169: fix VM update template

### LINKED ISSUE #169: OS section is deleted when updating CONTEXT
Hi,

I'm actively continuing my tests with the almost latest version of the master branch 😃 

I'm currently using the branch `treywelsh:B-167`, which is the most up-to-date master branch that is working after the recent problems we had with building from master.

I found another possible problem : When running `terraform apply` to update the `CONTEXT` values of an existing VM, the `OS` values are deleted.

For example, after running `terraform apply`, when I go on the VM from the UI, and I click on `Update` > `Advanced` Tab, the following block is gone :
```
OS = [
  ARCH = "x86_64",
  BOOT = "disk0",
  UUID = "271d0115-27ea-4464-ba4f-023f1d9a3e43" ]
```

### PR DESCRIPTION
**Pull request by treywelsh**
PR #145 enabled VM config update with some bad behavior due to a misunderstanding of the ONE API.

### CODE REVIEW

File: opennebula/resource_opennebula_virtual_machine.go [hunk 1]
```diff
@@ -1261,15 +1261,79 @@ func resourceOpennebulaVirtualMachineUpdate(d *schema.ResourceData, meta interfa
 	}
 
 	updateConf := false
+
+	// retrieve only template sections managed by updateconf method
 	tpl := vm.NewTemplate()
+	for _, name := range []string{"OS", "FEATURES", "INPUT", "GRAPHICS", "RAW", "CONTEXT"} {
```
Comment (jaypif) [inline opennebula/resource_opennebula_virtual_machine.go:1267]: why in the following lines you work only on "OS", "GRAPHICS" and "CONTEXT".
Why not "FEATURES", "INPUT" or "RAW" ?

File: opennebula/resource_opennebula_virtual_machine.go [hunk 2]
```diff
@@ -1261,15 +1261,79 @@ func resourceOpennebulaVirtualMachineUpdate(d *schema.ResourceData, meta interfa
...
+	}
 
 	if d.HasChange("os") {
 		updateConf = true
 
 		log.Printf("[DEBUG] Update os")
 
-		//Generate OS definition
-		addOS(tpl, d.Get("os").([]interface{}))
+		old, new := d.GetChange("os")
```
Comment (jaypif) [inline opennebula/resource_opennebula_virtual_machine.go:1279]: it seems you use the same pattern for "os", "graphics" and "context", maybe use a function instead ?

**Review by jaypif — CHANGES_REQUESTED** [review]

File: opennebula/resource_opennebula_virtual_machine.go (hunk 1 above)
Comment (treywelsh) [reply opennebula/resource_opennebula_virtual_machine.go:1267]: I copy these sections only, from the existing VM template, because the method updateconf take them into account:
https://docs.opennebula.io/5.12/integration/system_interfaces/api.html#one-vm-updateconf

If I don't copy one of these fields, it would be erased. See `OS` deletion problem when updating CONTEXT in #169 .
The RAW field is managed through the template resource, I didn't enabled it in VM resource, here is the original issue about this section: https://github.com/OpenNebula/terraform-provider-opennebula/issues/123
Do we need it in VM resource ?

For other parts FEATURES and INPUT there aren't managed at all.

This is not the goal of this issue, but to manage additional VM sections we could open a new issue (probably better) or just add them to https://github.com/OpenNebula/terraform-provider-opennebula/pull/154

File: opennebula/resource_opennebula_virtual_machine.go (hunk 2 above)
Comment (treywelsh) [reply opennebula/resource_opennebula_virtual_machine.go:1279]: done

File: opennebula/resource_opennebula_virtual_machine.go (hunk 1 above)
Comment (jaypif) [reply opennebula/resource_opennebula_virtual_machine.go:1267]: perfect thx

**Review by jaypif — APPROVED** [review]

**Comment by Th0masL** [comment]
Thanks guys for your great work ! 👏 👍
