### PR TITLE
B-92: Fix quotas in terraform state

### LINKED ISSUE #92: Do not set quotes in state if not present in the resource
Terraform detects a change because quotas is set as a Set with empty elements in the terraform state event if there are no quotas defined in user or groups.

### PR DESCRIPTION
**Pull request by jaypif**
Fix #92

### CODE REVIEW

File: opennebula/quotas.go [hunk 1]
```diff
@@ -191,48 +215,178 @@ func flattenQuotasMapFromStructs(d *schema.ResourceData, quotas *shared.QuotasLi
...
+				"datastore_quotas": datastoreQuotas,
+			},
+		})
+	case 0x02:
+		return d.Set("quotas", []interface{}{
+			map[string]interface{}{
+				"network_quotas": networkQuotas,
+			},
+		})
+	case 0x03:
```
Comment (treywelsh) [inline opennebula/quotas.go]: This works, but instead of making a case per combination (duplicate code), it would be possible to do something like:

```
const (
    F0 uint8 = 1
    F1          = 2
    F2          = 4
)

func main() {
	flags := F0
	flags = flags | F2
	
	for flags > 0 {
		switch {
			case flags & F0 > 0:
				// code for F0 here
				flags = flags ^ F0
			case flags & F1 > 0:
				// code for F1 here
				flags = flags ^ F1
			case flags & F2 > 0:
				// code for F2 here
				flags = flags ^ F2
		}
	}
}
```
With more explicit name for flags instead of FN.

In addition:
- the same map could be used, adding key, values in it at each loop iteration
- `return d.Set("quotas",` could be done once, after the loop.

Readability may be improved a bit, introducing some bitset functions (or use an external package like https://pkg.go.dev/github.com/willf/bitset):
```
...
func Set(b, flag uint8) uint8    { return b | flag }
func Clear(b, flag uint8) uint8  { return b &^ flag }
func Toggle(b, flag uint8) uint8 { return b ^ flag }
...
```

File: opennebula/quotas.go [hunk 2]
```diff
@@ -191,48 +215,178 @@ func flattenQuotasMapFromStructs(d *schema.ResourceData, quotas *shared.QuotasLi
 	var imageQuotas []map[string]interface{}
 	var vmQuotas []map[string]interface{}
 	var networkQuotas []map[string]interface{}
+	q := 0
```
Comment (treywelsh) [inline opennebula/quotas.go]: a slightly more explicit name could be used: flags, fields .... ?

**Review by treywelsh — APPROVED** [review]
